---
- hosts: all
  become: yes
  become_user: root
  
  
  tasks:
        
    - name: Enablle port 8080 on firewall
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Install pip
      yum:
        name: python-pip
        state: present
        
    - name: install flask
      pip:
        name: flask
        

    - name: clone the git repo
      git:
        repo: 'https://github.com/prideven/Ansible_CMP272_Hw1'
        dest: /home/root/Ansible_CMP272_Hw1
        update: no

        
    - name: run flask server for CentOs1
      shell: python CentOS1.py
      args:
        chdir: "/home/root/Ansible_CMP272_Hw1"
        
    - name: run flask server for CentOs2
      shell: python CentOS2.py
      args:
        chdir: "/home/root/Ansible_CMP272_Hw1"

  handlers:
  - name: restart flask app
    service: name=flask-demo state=restarted
