---
# Setting up system packages required to deploy Flask app
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Add epel -release repo
      yum:
        name: epel-release
        
    - name: Enable port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        
    - name: Reload Firewall service
      systemd:
        name: firewalld
        state: reloaded

    - name: Install pip
      yum:
        name: python-pip
        state: present

    - name: Clone git repo
      git:
        repo: 'https://github.com/prideven/Ansible'
        dest: /home/root/Ansible
        update: no 

    - name: Enable flask in systemd file
      shell: 
        cmd: cp -f /home/root/Ansible/demo.service /etc/systemd/system

    - name: Initialize the Dependencies
      pip:
        requirements: requirements.txt
        chdir: /home/root/Ansible
        
    - name: Run flaskapp on Centos
      shell: python Hello_World.py
      args:
        chdir: "/home/root/Ansible"

  handlers:
  - name: Restart Flaskapp
    service: name=flask-demo state=restarted
