---
- hosts: all
  become: yes
  become_user: root
  
  
  tasks:
        
    - name: Enablle port 8080 on firewall
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Install pip
      yum:
        name: python-pip
        state: present
        
    - name: install flask
      pip:
        name: flask
        

    - name: clone the git repo
      git:
        repo: 'https://github.com/prideven/Ansible'
        dest: /home/root/Ansible
        update: no

        
    - name: run flask server for CentOs
      shell: python Hello_World.py
      args:
        chdir: "/home/root/Ansible"
        

  handlers:
  - name: restart flask app
    service: name=flask-demo state=restarted
